[build]
dockerfile = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"

[[services]]
name = "code-server"

[services.env]
PORT = "8080"
START_DIR = "/home/coder/project"

[services.healthcheck]
path = "/"
timeout = 100 